doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host: '%env(resolve:DB_HOSTNAME)%'
                dbname: '%env(resolve:DB_NAME)%'
                user: '%env(resolve:DB_USERNAME)%'
                password: '%env(resolve:DB_PASSWORD)%'
                port: '%env(resolve:DB_PORT)%'
                driver: 'pdo_pgsql'
                server_version: '11.1'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
