framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus: ~

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            commands:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/commands'

            sync: 'sync://'

        routing:
            '*': sync
