services:
  App\Payroll\Domain\Workers: '@App\Payroll\Infrastructure\Doctrine\ORM\Domain\DoctrineORMWorkers'
  App\Payroll\Domain\Departments: '@App\Payroll\Infrastructure\Doctrine\ORM\Domain\DoctrineORMDepartments'
  App\Payroll\Domain\Payrolls: '@App\Payroll\Infrastructure\Doctrine\ORM\Domain\DoctrineORMPayrolls'
