parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\UserInterface\Http\Web\:
        resource: '../src/Payroll/UserInterface/Http/Web/'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Common\Application\Command\Handler:
            tags: [messenger.message_handler]
